
package com.oop.form;

import com.raven.datechooser.SelectedDate;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
/**
 *
 * @author Will
 */
public class FormCreate extends javax.swing.JPanel {

    Connection con;
    public FormCreate() {
        initComponents();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/raportku", "root", "");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton3 = new javax.swing.JRadioButton();
        dateChooser1 = new com.raven.datechooser.DateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        create_button1 = new Component.create_button();
        jLabel5 = new javax.swing.JLabel();

        jRadioButton3.setText("jRadioButton3");

        dateChooser1.setDateFormat("yyyy-MM-dd");
        dateChooser1.setTextRefernce(txtDate);

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        jLabel1.setText("Create");
        add(jLabel1);
        jLabel1.setBounds(266, 31, 260, 57);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Siswa");
        add(jLabel2);
        jLabel2.setBounds(190, 140, 120, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(290, 140, 176, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nama Siswa");
        add(jLabel3);
        jLabel3.setBounds(190, 176, 110, 30);
        add(jTextField2);
        jTextField2.setBounds(290, 180, 176, 22);

        txtDate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        add(txtDate);
        txtDate.setBounds(290, 220, 180, 22);

        jRadioButton1.setText("Male");
        add(jRadioButton1);
        jRadioButton1.setBounds(300, 260, 80, 21);

        jRadioButton2.setText("Female");
        add(jRadioButton2);
        jRadioButton2.setBounds(390, 260, 80, 21);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal Lahir");
        add(jLabel4);
        jLabel4.setBounds(190, 220, 90, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Gender");
        add(jLabel6);
        jLabel6.setBounds(190, 260, 90, 20);

        create_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_button1MouseClicked(evt);
            }
        });
        create_button1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                create_button1KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Create");

        javax.swing.GroupLayout create_button1Layout = new javax.swing.GroupLayout(create_button1);
        create_button1.setLayout(create_button1Layout);
        create_button1Layout.setHorizontalGroup(
            create_button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        create_button1Layout.setVerticalGroup(
            create_button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(create_button1);
        create_button1.setBounds(260, 300, 170, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void create_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_button1MouseClicked
        String id_siswa = jTextField1.getText();
        String nama_siswa = jTextField2.getText();
        String gender="";
        String date = txtDate.getText();
        if(jRadioButton1.isSelected()){
            gender = "Male";
        }else if (jRadioButton2.isSelected()){
            gender = "Female";
        }else{
            JOptionPane.showMessageDialog(jRadioButton1,"Mohon gender di isi");
        }
        System.out.println(date);
        String sql = "INSERT INTO `datasiswa` (`id_siswa`, `nama_siswa`, `gender`, `tanggal_lahir`) VALUES (?, ?, ?, ?)";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, id_siswa);
            pst.setString(2, nama_siswa);
            pst.setString(3, gender);
            pst.setString(4, date);
            System.out.println(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(create_button1, "Data telah ditambahkan");
            System.out.println(sql);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_create_button1MouseClicked

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void create_button1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_create_button1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_create_button1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private Component.create_button create_button1;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
